export enum Category {
    FICTION = 'FICTION',
    NON_FICTION = 'NON_FICTION',
    SCIENCE = 'SCIENCE',
    HISTORY = 'HISTORY',
    BIOGRAPHY = 'BIOGRAPHY',
    ROMANCE = 'ROMANCE',
    OTHER = 'OTHER',
    ADVENTURE = 'ADVENTURE',
    FANTASY = 'FANTASY',
    POETRY = 'POETRY',
    ART = 'ART',
    NOVEL = 'NOVEL',
    THRILLER = 'THRILLER',
    PHILOSOPHY = 'PHILOSOPHY',
    RELIGION = 'RELIGION',
    TECHNOLOGY = 'TECHNOLOGY'
}