version: '1.0'
services:
#  mysql:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: books_project
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#    ports:
#      - "8080:80"
#    depends_on:
#      - mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql_data: