/**
 * Books Project
 * The nestjs booksproject API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MfaGenerateResponseDto { 
    /**
     * MFA secret key
     */
    secret: string;
    /**
     * QR code data URL for scanning
     */
    qrCode: string;
    /**
     * OTP Auth URL for manual setup
     */
    otpAuthUrl: string;
}

