export enum CategoryEnum {
  FICTION = 'Fiction',
  SCIENCE = 'Science',
  TECHNOLOGY = 'Technology',
  TRAVEL = 'Travel',
  FOOD = 'Food',
  LIFESTYLE = 'Lifestyle',
  All = 'All',
  NON_FICTION = 'Non-Fiction',
  HISTORY = 'History',
  BIOGRAPHY = 'Biography',
  ROMANCE = 'Romance',
  OTHER = 'Other',
  ADVENTURE = 'Adventure',
  FANTASY = 'Fantasy',
  POETRY = 'Poetry',
  ART = 'Art',
  NOVEL = 'Novel',
  THRILLER = 'Thriller',
  PHILOSOPHY = 'Philosophy',
  RELIGION = 'Religion',
}
